export const networks = [
  {
    label: 'Fanbase',
    title: 'Fanbase Dollars',
    color: '#0162d0',
    logo: require('../../assets/NetworkLogo/fanbase.png'),
    sidebarLogo: require('../../assets/LeftSidebar/fanbase.png'),
    currency: 'FNBD',
    name: 'fnbd',
  },
  {
    label: 'Main Ethereum',
    title: 'Main Ethereum Network',
    color: '#008000',
    logo: require('../../assets/NetworkLogo/mainetherum.png'),
    sidebarLogo: require('../../assets/LeftSidebar/mainetherum.png'),
    currency: 'ETH',
    name: 'fnbd',
  },
  {
    label: 'Ropsten',
    title: 'Ropsten Network',
    color: '#ff6754',
    logo: require('../../assets/NetworkLogo/ropsten.png'),
    sidebarLogo: require('../../assets/LeftSidebar/ropsten.png'),
    currency: 'ETH',
    name: 'ropsten',
  },
  {
    label: 'Kovan Test',
    title: 'Kovan Test Network',
    color: '#5c3ec3',
    logo: require('../../assets/NetworkLogo/kovan.png'),
    sidebarLogo: require('../../assets/LeftSidebar/kovan.png'),
    currency: 'ETH',
    name: 'rinkeby',
  },
];
