import { Dimensions, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  headerContainer: {
    backgroundColor: '#f2f3f4',
    height: 120,
    width: Dimensions.get('screen').width,
    marginLeft: -15,
    paddingHorizontal: 15,
  },
  headerText: {
    alignSelf: 'center',
  },
  switchLogo: {
    height: 30,
    width: 30,
  },
  inputStyle: {
    backgroundColor: 'white',
    color: '#037DD6',
    paddingLeft: 10,
    borderRadius: 8,
    borderColor: '#037DD6',
    borderWidth: 1,
    height: 50,
    marginTop: 15,
  },
  itemsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  itemContainerText: {
    fontSize: 16,
    color: 'gray',
  },
  cardContainer: {
    width: 230,
    minWidth: 250,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#dedede',
    backgroundColor: '#fff',
    borderRadius: 4,
    fontSize: 12,
    color: '#4d4d4d',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    height: 100,
    padding: 10,
  },
  ETHLogo: {
    width: 30,
    height: 30,
  },
  ETHLogoHolder: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: '#dedede',
    borderRadius: 50,
    width: 45,
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemContainerTextHolder: {
    marginLeft: 15,
  },
  itemContainerCardText: {
    marginBottom: 35,
    fontSize: 16,
    color: '#5d5d5d',
  },
  itemContainerCardSubText: {
    fontSize: 12,
    color: 'gray',
  },
  ETHBlockContainer: {
    flexDirection: 'row',
  },
  ETHCalculatorContainer: {
    width: 230,
    minWidth: 250,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#dedede',
    backgroundColor: '#fff',
    borderRadius: 4,
    fontSize: 12,
    color: '#4d4d4d',
    display: 'flex',
    height: 70,
    padding: 10,
  },
  ETHCalculator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ETHCalculatorText: {
    fontSize: 12,
    color: '#4d4d4d',
  },
  ETHCalculatorValute: {
    paddingBottom: 15,
  },
  transactionFeeChoices: {
    width: 230,
    minWidth: 250,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#dedede',
    backgroundColor: '#fff',
    borderRadius: 4,
    fontSize: 12,
    color: '#4d4d4d',
    height: 80,
    padding: 5,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  buttonStyle: {
    backgroundColor: 'white',
    borderStyle: 'solid',
    borderWidth: 2,
    borderColor: '#B0D7F2',
    alignItems: 'center',
    width: 56,
    height: 20,
    marginTop: 15,
    borderRadius: 4,
  },
  clickedButton: {
    backgroundColor: 'white',
    borderStyle: 'solid',
    borderWidth: 2,
    borderColor: '#037DD6',
    alignItems: 'center',
    width: 56,
    height: 20,
    marginTop: 15,
    borderRadius: 4,
  },
  buttonText: {
    fontSize: 12,
    color: '#037DD6',
  },
  buttonsContainer: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    marginTop: 40,
  },
  advancedOptionsView: {
    alignItems: 'flex-end',
    marginTop: 20,
    marginRight: 15,
  },
  advancedOptionsText: {
    color: '#2f9ae0',
  },
  sendEther: {
    width: 230,
    minWidth: 250,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#dedede',
    borderRadius: 4,
    backgroundColor: '#fff',
    padding: 10,
    height: 80,
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  sendEtherContainer: {
    marginTop: 10,
  },
  sendEtherText: {
    color: '#5d5d5d',
    fontSize: 16,
    lineHeight: 22,
  },
});
